use CS144;

LOAD DATA LOCAL INFILE 'User.csv' INTO TABLE Ebay_Users
FIELDS TERMINATED BY '~~|}';

LOAD DATA LOCAL INFILE 'Auction.csv' INTO TABLE Auction
FIELDS TERMINATED BY '~~|}';

LOAD DATA LOCAL INFILE 'Bids.csv' INTO TABLE Bids
FIELDS TERMINATED BY '~~|}';

LOAD DATA LOCAL INFILE 'Buy_Price.csv' INTO TABLE Buy_Price
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Category.csv' INTO TABLE Category
FIELDS TERMINATED BY '~~|}';
